export const ACTION_TYPE = {
	ADD_ORDER: 'ADD_ORDER',
	LOAD_ORDERS: 'LOAD_ORDERS',
	LOAD_REQUESTED: 'LOAD_REQUESTED',
	LOAD_ORDERS_REQUESTED_FAILED: 'LOAD_ORDERS_REQUESTED_FAILED',
	LOGIN: 'LOGIN',
	LOGOUT: 'LOGOUT',
};
